logging.level:
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.zaxxer.hikari: TRACE
  org.hibernate.SQL: DEBUG
  org.hibernate.orm.jdbc.bind: TRACE
  root: INFO

server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: local
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:./data/laboratory;MODE=MySQL;
    username: sa
    password:
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
      defer-datasource-initialization: true
  redis:
    host: localhost
    port: 6380