logging:
  level:
    root: INFO

server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: local
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/laboratory
    username: root
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
      defer-datasource-initialization: true
  redis:
    host: localhost
    port: 6380